apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Chart.Name }}
spec:
  containers:
  - image: {{ .Values.redis_image.repository }}:{{ .Values.redis_image.tag }}
    name: redis
